apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: gluu # Can be set to prefix
  labels:
    cluster: gluu-couchbase
spec:
  name: gluu # Can be set to prefix
  memoryQuota: 100Mi
  replicas: 1
  ioPriority: low
  evictionPolicy: valueOnly
  conflictResolution: seqno
  enableFlush: true
  enableIndexReplica: false
  compressionMode: passive
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: gluu-site # Can be set to prefix-site
  labels:
    cluster: gluu-couchbase
spec:
  name: gluu_site  # Can be set to prefix_site
  memoryQuota: 100Mi
  replicas: 1
  ioPriority: low
  evictionPolicy: valueOnly
  conflictResolution: seqno
  enableFlush: true
  enableIndexReplica: false
  compressionMode: passive
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: gluu-user # Can be set to prefix-user
  labels:
    cluster: gluu-couchbase
spec:
  name: gluu_user  # Can be set to prefix_user
  memoryQuota: 100Mi
  replicas: 1
  ioPriority: high
  evictionPolicy: valueOnly
  conflictResolution: seqno
  enableFlush: true
  enableIndexReplica: false
  compressionMode: passive
