swagger: "2.0"
info:
  description: "This API will be used by Gluu / Gluu partners to grab the stats file which is in encrypted form and contains casa usage data."
  version: "4.0.0"
  title: "Gluu casa stats file Grab"
  
  license:
    name: "Gluu casa"
    url: "https://gluu.org/docs/casa/#license"
host: "madhu-ubu16.infinity.com"
basePath: "/casa/rest"
tags:
- name: "billing"
  description: "Related to billing for casa"
  
consumes:
- text/plain

produces:
- application/octet-stream
- text/plain

schemes:
- "https"

paths:
  /billing/usage/{month}/{year}:
  
    get:
      tags:
      - "usage"
      summary: "Grab usage file for given month and year"
      description: "Returns a single file containing encrypted usage stats for a given month and year"
      
      produces:
      - "application/octet-stream"
      - "text/plain"
      parameters:
      - name: "month"
        in: "path"
        description: "month for which stats file is being requested"
        required: true
        type: "integer"
        format: "int64"
      - name: "year"
        in: "path"
        description: "year for which stats file is being requested"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
         
        400:
          description: "Incorrect month / year"
        404:
          description: "File not found for given month and year"
      